name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  claude-review:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Get PR diff
      id: diff
      run: |
        # Get the diff between base and head
        git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} > pr_diff.txt
        
        # Limit diff size to avoid API limits (max ~8000 tokens)
        head -n 500 pr_diff.txt > pr_diff_limited.txt
        
        # Get list of changed files
        git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} > changed_files.txt
        
        # Create a summary
        echo "Changed files:" > pr_summary.txt
        cat changed_files.txt >> pr_summary.txt
        echo -e "\n\nDiff preview (first 500 lines):" >> pr_summary.txt
        cat pr_diff_limited.txt >> pr_summary.txt
    
    - name: Check Claude Code CLI
      run: |
        # Check if Claude Code CLI is available
        if ! command -v claude &> /dev/null; then
          echo "Claude Code CLI not found. Please install it on the self-hosted runner:"
          echo "See: https://docs.anthropic.com/en/docs/claude-code/quickstart"
          exit 1
        fi
        
        # Check Claude Code version and authentication
        claude --version
        echo "Claude Code CLI is available and ready to use with your subscription"
        
    - name: Review with Claude Code
      id: claude_review
      run: |
        # Create review prompt
        cat > review_prompt.txt << 'EOF'
        You are a senior code reviewer. Please review this pull request and provide constructive feedback.

        Focus on:
        1. Code quality and best practices
        2. Potential bugs or issues  
        3. Security concerns
        4. Performance considerations
        5. Suggestions for improvement

        Be specific and actionable in your feedback. If the code looks good, say so!

        PR Title: ${{ github.event.pull_request.title }}
        PR Description: ${{ github.event.pull_request.body }}

        Changes:
        EOF
        
        # Append the PR content
        cat pr_summary.txt >> review_prompt.txt
        
        # Get review from Claude Code CLI using --print for non-interactive mode
        claude --print --model haiku "$(cat review_prompt.txt)" > claude_review.md 2>&1
        
        # Check if review was successful
        if [ $? -ne 0 ]; then
          echo "Error: Claude Code review failed"
          echo "Failed to get review from Claude Code CLI" > claude_review.md
        fi
    
    - name: Post review comment
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const review = fs.readFileSync('claude_review.md', 'utf8');
          
          const comment = `## 🤖 Claude Code Review\n\n${review}\n\n---\n*This is an automated code review by Claude AI. Please consider the suggestions but use your judgment.*`;
          
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: comment
          });